{*lock tables linkage_commissioner, linkage_shared_field write;*}

INSERT INTO
	linkage_commissioner(
		book_no,
		status,
		set_date,
		data_type_2,
		send_type_1,
		source_type_1,
		source_code_1,
		to_type_1,
		to_code_1,
		c_stamp_1,
		record_type_1,
		cancell_type_1,
		category_code_1,
		trade_code_1,
		trade_code_branch_1,
		issuer_1,
		issuer_kana_1,
		publisher_2,
		publisher_kana_2,
		handling_company_1,
		handling_type_1,
		series_1,
		series_kana_1,
		series_volume_1,
		sub_series_1,
		sub_series_kana_1,
		sub_series_volume_1,
		total_volume_1,
		total_other_volume_1,
		distribution_count_1,
		name_1,
		kana_1,
		volume_2,
		sub_1,
		sub_kana_1,
		sub_volume_1,
		end_1,
		present_volume_1,
		author_1,
		author_kana_1,
		author_type_1,
		author_2,
		author_kana_2,
		author_type_2,
		author_3,
		author_kana_3,
		author_type_3,
		content_1,
		content_2,
		preliminary_5,
		book_size_2,
		book_size_3,
		page_1,
		bound_1,
		release_date_1,
		return_date_1,
		notation_price_1,
		price_1,
		price_tax_1,
		price_special_1,
		price_special_tax_1,
		price_special_policy_1,
		distribution_type_1,
		distribut_1,
		isbn_1,
		category_1,
		magazine_code_2,
		magazine_code_1,
		adult_1,
		pre_order_1,
		order_status_1,
		circulation_1,
		fix_1,
		typist_1,
		typist_tel_1,
		type_date_1,
		edit_time_stamp_1,
		win_info_1,
		c_stamp
	)
	VALUES(
		{$book.book_no|escape},
		1,
		current_timestamp,
		'{$data_type_2}',
		'{$send_type_1}',
		'{$source_type_1}',
		'{$source_code_1}',
		'{$to_type_1}',
		'{$to_code_1}',
		'{$c_stamp_1}',
		'{$record_type_1}',
		'{if $cancell_type_1}1{/if}',
		{if !$uFields.category_code_1[$cType]}''{else}'{$category_code_1}'{/if},
		{if !$uFields.trade_code_1[$cType]}''{else}'{$trade_code_1}'{/if},
		{if !$uFields.trade_code_branch_1[$cType]}''{else}'{$trade_code_branch_1}'{/if},
		{if !$uFields.issuer_1[$cType]}''{else}'{$issuer_1}'{/if},
		{if !$uFields.issuer_kana_1[$cType]}''{else}'{$issuer_kana_1}'{/if},
		{if !$uFields.publisher_2[$cType]}''{else}'{$publisher_2}'{/if},
		{if !$uFields.publisher_kana_2[$cType]}''{else}'{$publisher_kana_2}'{/if},
		{if !$uFields.handling_company_1[$cType]}''{else}'{$handling_company_1}'{/if},
		{if !$uFields.handling_type_1[$cType]}''{else}'{$handling_type_1}'{/if},
		{if !$uFields.series_1[$cType]}''{else}'{$series_1}'{/if},
		{if !$uFields.series_kana_1[$cType]}''{else}'{$series_kana_1}'{/if},
		{if !$uFields.series_volume_1[$cType]}''{else}'{$series_volume_1}'{/if},
		{if !$uFields.sub_series_1[$cType]}''{else}'{$sub_series_1}'{/if},
		{if !$uFields.sub_series_kana_1[$cType]}''{else}'{$sub_series_kana_1}'{/if},
		{if !$uFields.sub_series_volume_1[$cType]}''{else}'{$sub_series_volume_1}'{/if},
		{if !$uFields.total_volume_1[$cType]}''{else}'{$total_volume_1}'{/if},
		{if !$uFields.total_other_volume_1[$cType]}''{else}'{$total_other_volume_1}'{/if},
		{if !$uFields.distribution_count_1[$cType]}''{else}'{$distribution_count_1}'{/if},
		{if !$uFields.name_1[$cType]}''{else}'{$name_1}'{/if},
		{if !$uFields.kana_1[$cType]}''{else}'{$kana_1}'{/if},
		{if !$uFields.volume_2[$cType]}''{else}'{$volume_2}'{/if},
		{if !$uFields.sub_1[$cType]}''{else}'{$sub_1}'{/if},
		{if !$uFields.sub_kana_1[$cType]}''{else}'{$sub_kana_1}'{/if},
		{if !$uFields.sub_volume_1[$cType]}''{else}'{$sub_volume_1}'{/if},
		{if !$uFields.end_1[$cType]}''{else}'{$end_1}'{/if},
		{if !$uFields.present_volume_1[$cType]}''{else}'{$present_volume_1}'{/if},
		{if !$uFields.author_1[$cType]}''{else}'{$author_1}'{/if},
		{if !$uFields.author_kana_1[$cType]}''{else}'{$author_kana_1}'{/if},
		{if !$uFields.author_type_1[$cType]}''{else}'{$author_type_1}'{/if},
		{if !$uFields.author_2[$cType]}''{else}'{$author_2}'{/if},
		{if !$uFields.author_kana_2[$cType]}''{else}'{$author_kana_2}'{/if},
		{if !$uFields.author_type_2[$cType]}''{else}'{$author_type_2}'{/if},
		{if !$uFields.author_3[$cType]}''{else}'{$author_3}'{/if},
		{if !$uFields.author_kana_3[$cType]}''{else}'{$author_kana_3}'{/if},
		{if !$uFields.author_type_3[$cType]}''{else}'{$author_type_3}'{/if},
		{if !$uFields.content_1[$cType]}''{else}'{$content_1}'{/if},
		{if !$uFields.content_2[$cType]}''{else}'{$content_2}'{/if},
		{if !$uFields.preliminary_5[$cType]}''{else}'{$preliminary_5}'{/if},
		{if !$uFields.book_size_2[$cType]}''{else}'{$book_size_2}'{/if},
		{if !$uFields.book_size_3[$cType]}''{else}'{$book_size_3}'{/if},
		{if !$uFields.page_1[$cType]}''{else}'{$page_1}'{/if},
		{if !$uFields.bound_1[$cType]}''{else}'{$bound_1}'{/if},
		{if !$uFields.release_date_1[$cType]}''{else}'{$release_date_1}'{/if},
		{if !$uFields.return_date_1[$cType]}''{else}'{$return_date_1}'{/if},
		{if !$uFields.notation_price_1[$cType]}''{else}'{$notation_price_1}'{/if},
		{if !$uFields.price_1[$cType]}''{else}'{$price_1}'{/if},
		{if !$uFields.price_tax_1[$cType]}''{else}'{$price_tax_1}'{/if},
		{if !$uFields.price_special_1[$cType]}''{else}'{$price_special_1}'{/if},
		{if !$uFields.price_special_tax_1[$cType]}''{else}'{$price_special_tax_1}'{/if},
		{if !$uFields.price_special_policy_1[$cType]}''{else}'{$price_special_policy_1}'{/if},
		{if !$uFields.distribution_type_1[$cType]}''{else}'{$distribution_type_1}'{/if},
		{if !$uFields.distribut_1[$cType]}''{else}'{$distribut_1}'{/if},
		{if !$uFields.isbn_1[$cType]}''{else}'{$isbn_1}'{/if},
		{if !$uFields.category_1[$cType]}''{else}'{$category_1}'{/if},
		{if !$uFields.magazine_code_2[$cType]}''{else}'{$magazine_code_2}'{/if},
		{if !$uFields.magazine_code_1[$cType]}''{else}'{$magazine_code_1}'{/if},
		{if !$uFields.adult_1[$cType]}''{else}'{$adult_1}'{/if},
		{if !$uFields.pre_order_1[$cType]}''{else}'{$pre_order_1}'{/if},
		{if !$uFields.order_status_1[$cType]}''{else}'{$order_status_1}'{/if},
		{if !$uFields.circulation_1[$cType]}''{else}'{$circulation_1}'{/if},
		{if !$uFields.fix_1[$cType]}''{else}'{$fix_1}'{/if},
		{if !$uFields.typist_1[$cType]}''{else}'{$typist_1}'{/if},
		{if !$uFields.typist_tel_1[$cType]}''{else}'{$typist_tel_1}'{/if},
		{if !$uFields.type_date_1[$cType]}''{else}'{$type_date_1}'{/if},
		{if !$uFields.edit_time_stamp_1[$cType]}''{else}'{$edit_time_stamp_1}'{/if},
		{if !$uFields.win_info_1[$cType]}''{else}'{$win_info_1}'{/if},
		now()
	)
ON DUPLICATE KEY
	UPDATE
		status = values(status),
		set_date = values(set_date),
		data_type_2=values(data_type_2),
		send_type_1=values(send_type_1),
		source_type_1=values(source_type_1),
		source_code_1=values(source_code_1),
		to_type_1=values(to_type_1),
		to_code_1=values(to_code_1),
		c_stamp_1=values(c_stamp_1),
		record_type_1=values(record_type_1),
		cancell_type_1=values(cancell_type_1),
		category_code_1=values(category_code_1),
		trade_code_1=values(trade_code_1),
		trade_code_branch_1=values(trade_code_branch_1),
		issuer_1=values(issuer_1),
		issuer_kana_1=values(issuer_kana_1),
		publisher_2=values(publisher_2),
		publisher_kana_2=values(publisher_kana_2),
		handling_company_1=values(handling_company_1),
		handling_type_1=values(handling_type_1),
		series_1=values(series_1),
		series_kana_1=values(series_kana_1),
		series_volume_1=values(series_volume_1),
		sub_series_1=values(sub_series_1),
		sub_series_kana_1=values(sub_series_kana_1),
		sub_series_volume_1=values(sub_series_volume_1),
		total_volume_1=values(total_volume_1),
		total_other_volume_1=values(total_other_volume_1),
		distribution_count_1=values(distribution_count_1),
		name_1=values(name_1),
		kana_1=values(kana_1),
		volume_2=values(volume_2),
		sub_1=values(sub_1),
		sub_kana_1=values(sub_kana_1),
		sub_volume_1=values(sub_volume_1),
		end_1=values(end_1),
		present_volume_1=values(present_volume_1),
		author_1=values(author_1),
		author_kana_1=values(author_kana_1),
		author_type_1=values(author_type_1),
		author_2=values(author_2),
		author_kana_2=values(author_kana_2),
		author_type_2=values(author_type_2),
		author_3=values(author_3),
		author_kana_3=values(author_kana_3),
		author_type_3=values(author_type_3),
		content_1=values(content_1),
		content_2=values(content_2),
		preliminary_5=values(preliminary_5),
		book_size_2=values(book_size_2),
		book_size_3=values(book_size_3),
		page_1=values(page_1),
		bound_1=values(bound_1),
		release_date_1=values(release_date_1),
		return_date_1=values(return_date_1),
		notation_price_1=values(notation_price_1),
		price_1=values(price_1),
		price_tax_1=values(price_tax_1),
		price_special_1=values(price_special_1),
		price_special_tax_1=values(price_special_tax_1),
		price_special_policy_1=values(price_special_policy_1),
		distribution_type_1=values(distribution_type_1),
		distribut_1=values(distribut_1),
		isbn_1=values(isbn_1),
		category_1=values(category_1),
		magazine_code_2=values(magazine_code_2),
		magazine_code_1=values(magazine_code_1),
		adult_1=values(adult_1),
		pre_order_1=values(pre_order_1),
		order_status_1=values(order_status_1),
		circulation_1=values(circulation_1),
		fix_1=values(fix_1),
		typist_1=values(typist_1),
		typist_tel_1=values(typist_tel_1),
		type_date_1=values(type_date_1),
		edit_time_stamp_1=values(edit_time_stamp_1),
		win_info_1=values(win_info_1)
;


{foreach from=$fieldList item=field}

INSERT INTO
	linkage_shared_field(
		field_id,
		book_no,
		table_id
	)values(
		'{$field}',
		{$book.book_no|escape},
		'commissioner'
	)
on DUPLICATE KEY
	UPDATE
		table_id = VALUES(table_id)
;

{/foreach}


{*unlock tables;*}
