SELECT
	data_type_2,
	send_type_1,
	source_type_1,
	source_code_1,
	to_type_1,
	to_code_1,
	c_stamp_1,
	record_type_1,
	cancell_type_1,
	category_code_1,
	trade_code_1,
	trade_code_branch_1,
	issuer_1,
	issuer_kana_1,
	publisher_2,
	publisher_kana_2,
	handling_company_1,
	handling_type_1,
	series_1,
	series_kana_1,
	series_volume_1,
	sub_series_1,
	sub_series_kana_1,
	sub_series_volume_1,
	total_volume_1,
	total_other_volume_1,
	distribution_count_1,
	name_1,
	kana_1,
	volume_2,
	sub_1,
	sub_kana_1,
	sub_volume_1,
	end_1,
	present_volume_1,
	author_1,
	author_kana_1,
	author_type_1,
	author_2,
	author_kana_2,
	author_type_2,
	author_3,
	author_kana_3,
	author_type_3,
	content_1,
	content_2,
	preliminary_5,
	book_size_2,
	if(LOCATE('x', book_size_3)=0,'',substring_index(book_size_3,'x',1)) as book_size_3_l,
	if(LOCATE('x', book_size_3)=0,'',substring_index(book_size_3,'x',-1)) as book_size_3_r,
	page_1,
	bound_1,
	release_date_1,
	SUBSTRING(release_date_1,1,4) as release_date_1_year,
	SUBSTRING(release_date_1,5,2) as release_date_1_month,
	SUBSTRING(release_date_1,7,2) as release_date_1_day,
	return_date_1,
	SUBSTRING(return_date_1,1,4) as return_date_1_year,
	SUBSTRING(return_date_1,5,2) as return_date_1_month,
	SUBSTRING(return_date_1,7,2) as return_date_1_day,
	notation_price_1 ,
	price_1,
	price_tax_1,
	price_special_1,
	price_special_tax_1,
	price_special_policy_1,
	SUBSTRING(price_special_policy_1,1,4) as price_special_policy_1_year,
	SUBSTRING(price_special_policy_1,5,2) as price_special_policy_1_month,
	SUBSTRING(price_special_policy_1,7,2) as price_special_policy_1_day,
	distribution_type_1,
	distribut_1,
	isbn_1,
	category_1,
	magazine_code_2,
	if(LOCATE('/', magazine_code_1)=0,SUBSTRING(magazine_code_1,1,5),'') as magazine_code_1_1_1,
	if(LOCATE('/', magazine_code_1)=0,SUBSTRING(magazine_code_1,7,2),'') as magazine_code_1_1_2,
	if(LOCATE('/', magazine_code_1)=0,'',SUBSTRING(magazine_code_1,1,5)) as magazine_code_1_2_1,
	if(LOCATE('/', magazine_code_1)=0,'',SUBSTRING(magazine_code_1,7,2)) as magazine_code_1_2_2,
	if(LOCATE('/', magazine_code_1)=0,'',SUBSTRING(magazine_code_1,10,2)) as magazine_code_1_2_3,
	adult_1,
	pre_order_1,
	order_status_1,
	SUBSTRING(order_status_1,1,4) as order_status_1_year,
	SUBSTRING(order_status_1,5,2) as order_status_1_month,
	SUBSTRING(order_status_1,7,2) as order_status_1_day,
	circulation_1,
	fix_1,
	typist_1,
	typist_tel_1,
	type_date_1,
	SUBSTRING(type_date_1,1,4) as type_date_1_year,
	SUBSTRING(type_date_1,5,2) as type_date_1_month,
	SUBSTRING(type_date_1,7,2) as type_date_1_day,
	edit_time_stamp_1,
	SUBSTRING(edit_time_stamp_1,1,2) as edit_time_stamp_1_hour,
	SUBSTRING(edit_time_stamp_1,3,2) as edit_time_stamp_1_min,
	SUBSTRING(edit_time_stamp_1,5,2) as edit_time_stamp_1_sec,
	win_info_1

FROM linkage_commissioner as n

WHERE n.book_no = {$book_no}
	and exists(
		select *
		from book
		where
		book.book_no = n.book_no
		and book.publisher_no = {$publisher_no}
	)
;
